from __future__ import annotations

import logging
import re
import time
import unicodedata
from functools import lru_cache

import requests
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

try:
    from transformers import BitsAndBytesConfig
except ImportError:
    BitsAndBytesConfig = None

from src.core.setting_loader import load_settings
from src.llm.prompt import build_prompt


logger = logging.getLogger("llm")


def _get_llm_config() -> dict:
    return load_settings().get("llm", {})


def _normalize_for_filter(text: str) -> str:
    plain = "".join(
        character
        for character in unicodedata.normalize("NFKD", text or "")
        if not unicodedata.combining(character)
    )
    return re.sub(r"\s+", " ", plain).strip().lower()


def _clean_line(line: str) -> str:
    cleaned = line.strip().strip('"').strip("'")
    normalized = _normalize_for_filter(cleaned)

    for prefix in ["answer:", "tra loi:", "cau tra loi:", "response:"]:
        if normalized.startswith(prefix) and ":" in cleaned:
            cleaned = cleaned.split(":", 1)[1].strip()
            break

    return cleaned


def _remove_repeated_lines(lines: list[str]) -> list[str]:
    cleaned_lines = []
    seen = set()

    for line in lines:
        normalized = _normalize_for_filter(line)
        if not normalized or normalized.startswith("#") or normalized in seen:
            continue

        seen.add(normalized)
        cleaned_lines.append(line.strip())

    return cleaned_lines


def _is_meta_line(line: str) -> bool:
    normalized = _normalize_for_filter(line)
    meta_markers = [
        "bai tap",
        "hay thu",
        "toi rat mong",
        "mong cho phan hoi",
        "phan hoi tu ban",
        "chuc ban",
        "luu y",
        "ky nang",
        "tu duy logic",
    ]
    return any(marker in normalized for marker in meta_markers)


def _trim_meta_tail(lines: list[str]) -> list[str]:
    trimmed = []
    for line in lines:
        if _is_meta_line(line):
            break
        trimmed.append(line)
    return trimmed


def _truncate_prompt_echo(answer: str) -> str:
    markers = [
        "TRONG CONTEXT:",
        "CONTEXT:",
        "LICH SU HOI THOAI",
        "CAU HOI HIEN TAI:",
        "TRA LOI BANG TIENG VIET:",
    ]

    upper_answer = answer.upper()
    positions = [upper_answer.find(marker) for marker in markers if upper_answer.find(marker) != -1]
    if positions:
        answer = answer[: min(positions)].rstrip(" \n:-")

    return answer


def _truncate_disclaimer_tail(answer: str) -> str:
    lower_answer = answer.lower()
    markers = [
        "caution:",
        "the information provided is for informational purposes only",
        "generated by using ai",
        "generated by ai",
        "use it at your own risk",
        "this is just one example",
        "actual data might vary",
        "thank you for using our service",
        "consult a lawyer",
        "fictional",
        "copyright laws",
        "ethical guidelines",
        "unauthorized reproduction",
    ]

    positions = [lower_answer.find(marker) for marker in markers if lower_answer.find(marker) != -1]
    if positions:
        answer = answer[: min(positions)].rstrip(" \n:-")

    return answer


def _postprocess_answer(answer: str) -> str:
    answer = answer.strip()

    answer = _truncate_prompt_echo(answer)
    answer = _truncate_disclaimer_tail(answer)

    hashtag_pos = answer.find("#")
    if hashtag_pos != -1:
        answer = answer[:hashtag_pos].strip()

    answer = answer.replace("<|endoftext|>", " ").strip()

    raw_lines = [line for line in answer.splitlines()]
    raw_lines = [_clean_line(line) for line in raw_lines]
    raw_lines = [line for line in raw_lines if line.strip()]
    raw_lines = _remove_repeated_lines(raw_lines)
    raw_lines = _trim_meta_tail(raw_lines)

    answer = "\n".join(raw_lines).strip()
    answer = re.sub(r"\n{3,}", "\n\n", answer)
    answer = re.sub(r"[ \t]{2,}", " ", answer).strip()

    if not answer:
        answer = "Mình chưa tạo được câu trả lời phù hợp từ dữ liệu hiện tại."

    return answer


@lru_cache(maxsize=4)
def _build_huggingface_generator(
    model_name: str,
    model_device: str,
    trust_remote_code: bool,
    load_in_8bit: bool,
):
    logger.info("Loading Hugging Face model: %s", model_name)

    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=trust_remote_code,
    )

    model_kwargs = {
        "trust_remote_code": trust_remote_code,
    }

    if load_in_8bit:
        if BitsAndBytesConfig is None:
            raise RuntimeError("bitsandbytes chưa được cài nhưng load_in_8bit=true")
        model_kwargs["quantization_config"] = BitsAndBytesConfig(load_in_8bit=True)
        model_kwargs["device_map"] = "auto"
    elif model_device == "auto":
        model_kwargs["device_map"] = "auto"
        if torch.cuda.is_available():
            model_kwargs["torch_dtype"] = torch.float16
    elif model_device == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("CUDA không khả dụng nhưng llm.device='cuda'")
        model_kwargs["torch_dtype"] = torch.float16
    elif model_device != "cpu":
        raise ValueError("llm.device phải là một trong: auto, cpu, cuda")

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        **model_kwargs,
    )

    if model_device == "cuda" and not load_in_8bit:
        model = model.to("cuda")
    elif model_device == "cpu":
        model = model.to("cpu")

    if tokenizer.pad_token_id is None and tokenizer.eos_token_id is not None:
        tokenizer.pad_token = tokenizer.eos_token

    text_generator = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
    )

    logger.info("Hugging Face model loaded successfully.")
    return text_generator


def get_text_generator():
    llm_config = _get_llm_config()
    provider = llm_config.get("provider", "huggingface_local")
    if provider != "huggingface_local":
        raise ValueError(f"Unsupported model provider for local generator: {provider}")

    return _build_huggingface_generator(
        model_name=llm_config.get("model_name", "Qwen/Qwen2.5-1.5B-Instruct"),
        model_device=llm_config.get("device", "auto"),
        trust_remote_code=bool(llm_config.get("trust_remote_code", False)),
        load_in_8bit=bool(llm_config.get("load_in_8bit", False)),
    )


def _generate_with_huggingface(prompt: str, llm_config: dict) -> str:
    text_generator = get_text_generator()
    temperature = float(llm_config.get("temperature", 0.1))

    generate_kwargs = {
        "max_new_tokens": int(llm_config.get("max_tokens", 256)),
        "pad_token_id": text_generator.tokenizer.pad_token_id,
        "eos_token_id": text_generator.tokenizer.eos_token_id,
        "return_full_text": False,
        "num_return_sequences": 1,
        "repetition_penalty": 1.12,
        "no_repeat_ngram_size": 5,
    }

    if temperature > 0.15:
        generate_kwargs["do_sample"] = True
        generate_kwargs["temperature"] = temperature
        generate_kwargs["top_p"] = 0.9
    else:
        generate_kwargs["do_sample"] = False

    outputs = text_generator(prompt, **generate_kwargs)
    return outputs[0]["generated_text"].strip()


def _generate_with_ollama(prompt: str, llm_config: dict) -> str:
    model_name = llm_config.get("model_name", "qwen2.5:3b")
    base_url = llm_config.get("base_url", "http://localhost:11434").rstrip("/")
    timeout = int(llm_config.get("timeout", 180))

    response = requests.post(
        f"{base_url}/api/generate",
        json={
            "model": model_name,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": float(llm_config.get("temperature", 0.1)),
                "num_predict": int(llm_config.get("max_tokens", 256)),
            },
        },
        timeout=timeout,
    )
    response.raise_for_status()
    payload = response.json()
    return str(payload.get("response", "")).strip()


def generate_answer(context: str, question: str, conversation_history: str = "") -> str:
    if not context or not context.strip():
        logger.warning("Received empty context for answer generation.")
        return "Mình không tìm thấy đủ dữ liệu để trả lời câu hỏi này."

    if not question or not question.strip():
        logger.warning("Received empty question for answer generation.")
        return "Câu hỏi không được để trống."

    llm_config = _get_llm_config()
    provider = llm_config.get("provider", "huggingface_local")
    model_name = llm_config.get("model_name", "unknown")
    prompt = build_prompt(context, question, conversation_history=conversation_history)
    start = time.perf_counter()

    logger.info("Generating answer using provider=%s model=%s", provider, model_name)

    try:
        if provider == "huggingface_local":
            answer = _generate_with_huggingface(prompt, llm_config)
        elif provider == "ollama":
            answer = _generate_with_ollama(prompt, llm_config)
        else:
            raise ValueError(f"Unsupported model provider: {provider}")

        answer = _postprocess_answer(answer)
        logger.info(
            "Answer generation completed successfully. provider=%s model=%s latency_ms=%.2f",
            provider,
            model_name,
            (time.perf_counter() - start) * 1000,
        )
        return answer

    except torch.cuda.OutOfMemoryError:
        logger.error("Out of memory while loading/running model %s", model_name, exc_info=True)
        return "Model đang quá nặng cho bộ nhớ hiện tại. Hãy dùng model nhỏ hơn hoặc bật 8-bit quantization."
    except Exception as error:
        logger.error("Error during answer generation: %s", error, exc_info=True)
        return "Đã xảy ra lỗi trong quá trình tạo câu trả lời."
